addSbtPlugin("org.jetbrains.scala" % "sbt-ide-settings"   % "1.1.1")
addSbtPlugin("org.scalameta"       % "sbt-scalafmt"       % "2.5.2")
addSbtPlugin("com.github.sbt"      % "sbt-ci-release"     % "1.9.0")
addSbtPlugin("com.eed3si9n"        % "sbt-assembly"       % "2.3.0")
addSbtPlugin("com.github.sbt"      % "sbt-github-actions" % "0.24.0")
addSbtPlugin("com.typesafe"        % "sbt-mima-plugin"    % "1.1.4")
